language: python
cache: pip
python:
    - "3.8"
env:
  global:
    - secure: Z+Xr4OZ27QAxZW6oYI/pPNb+HZG2agL9hXvRmLI7FTrX/6/rSlDW3n1/E05+GY6gxotNxqDiVAtIk1Noa0PO47/YXCLlWY2QFSiEPOz8bmXoA70H09uZPnXreHIBHPy0BhukIWbcG/D4m5H51iwH4o0VFTGg9AQW6RrrUh+KRhdQQFoek/8Z1l3vo8RDxLowKTlYbGwmqDq77k7WzDU/KG+QJ3qOKOww/34FOhk+BgtRw/2vuIcGYq36R0sMIuXBhggHhXCJWPQ+L78PpLGrn9O6Til9ORFrC9RndYPyLhT8RKapjMpHmFagDZsjQr8+Q6wVyaSV86R5JIxA38faYLsrstcsfi4ABexHpqUH90OyTajby7WFnd2oZSEtro7HL8xWn6QvDKuCT0SFCmbSI+4PcXHAVcrDmu4aRb6vTFMHxH7pkHXeIZEllpPuQ9MIXNBtZWbyTs2hlZtEakqNXH4dOm5rvR4z7NHnh7WlVpDb4TslUWxWRxXezrQUfamHdamP/VYAyhqmoNhTasf+faU6P/LZFhldxiW1inMABpqrRELZ8ii/troIIvD60Z7ZMhP3MdgAmY0EMvdOvAZmW1t7M8mxr9iUpgA97UahgWYShTMALdmb+CX89OYiNXnxtTi68OHNjA0C+loSSpjhrLobtGT0MFn7+mpYcdDchbY=
    - secure: exNrHxINm+ckSF6zvTfTIGVTtYJo4bmpVIShya+0TYhZbptK1RsI2DnpsWBzPTdIC0GTkfkiZu2FXIgLcl3teY6S5Jm/o0fhHO1aXp/BCVwkAFeDuoUFruBeNXPpeqTC24ad7MjORaeqNyrt52WoN5+j0SUH5eVWi5eG4EVh0Y6K9onMH/uyJqbqL+I+wZ3oirYAprleu/agSBwz5vcczhs99IsLoLhI+SOn1epQnv57D15vK3VRkq1FoFnBS8CT9iAOeUDySIdKRHsJ0aLsH7+Z1msUND4FTx9NsSvmotKX2FqhkSjY5G76BenDqNpQmLgCZDy0HgoaLvDmw53BTUro9vu6Ut/+FzOapI7P+bqRZZVPupgMGKeisTOrFmW/t5jbW0RqXeKIG7i/Kknjiwr65fgAA5H0Ker3Kdt4X2qlh0npBPvBsLUhoAKHGXRjhf3Hb67lO14i+I/QNLPkj0dMgmh91feJ2L4JRlG7lCFsv1fuG6hCLKMV1meUmPjbwjmucmLOyKGKExTyu/OnvTZRoYN0mabhgKDCYi+hmkUNq4XgnEkJdv0W1Z+k/STnTIsvLarDBTxj63Slzc6Ls6fEgfq3RwEXNwfD7aBoEXw6iubCe3UPi1n1eWXtiR1iRrPcpcmYq2PcEGxBUgz1vvahaIbLZz5jyZXlzQCRGpk=
before_install:
    - echo $super_secret_password | gpg --passphrase-fd 0 .travis/git.gpg
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - coverage run manage.py test -v 2
    - pylint --output-format=text --exit-zero core tests
after_success:
    - coveralls
deploy:
    - provider: script
    - script: bash .travis/deploy.sh
    - on:
        - branch: master
