language: python
cache: pip
python:
    - "3.8"
before_install:
    - openssl aes-256-cbc -K $encrypted_7509e548d36f_key -iv $encrypted_7509e548d36f_iv
      -in .travis/git.enc -out .travis/git -d
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - coverage run manage.py test -v 2
    - pylint --output-format=text --exit-zero core tests
after_success:
    - coveralls
deploy:
    - provider: script
    - script: bash .travis/deploy.sh
    - on:
        - branch: master
